/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardWithdrawalRouteImport } from './routes/_dashboard/withdrawal'
import { Route as DashboardSectionRouteImport } from './routes/_dashboard/section'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardKycRouteImport } from './routes/_dashboard/kyc'
import { Route as DashboardDepositRouteImport } from './routes/_dashboard/deposit'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCopyRouteImport } from './routes/_dashboard/copy'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthOperationsRouteImport } from './routes/_auth/operations'
import { Route as AuthLogoutRouteImport } from './routes/_auth/logout'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotRouteImport } from './routes/_auth/forgot'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminUserReferralsRouteImport } from './routes/_admin/user-referrals'
import { Route as AdminUserKycRouteImport } from './routes/_admin/user-kyc'
import { Route as AdminTransactionsRouteImport } from './routes/_admin/transactions'
import { Route as AdminTradersRouteImport } from './routes/_admin/traders'
import { Route as AdminStaffRouteImport } from './routes/_admin/staff'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminNotifyRouteImport } from './routes/_admin/notify'
import { Route as AdminMeRouteImport } from './routes/_admin/me'
import { Route as AdminCopyTradingRouteImport } from './routes/_admin/copy-trading'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWithdrawalRoute = DashboardWithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSectionRoute = DashboardSectionRouteImport.update({
  id: '/section',
  path: '/section',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKycRoute = DashboardKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDepositRoute = DashboardDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCopyRoute = DashboardCopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOperationsRoute = AuthOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserReferralsRoute = AdminUserReferralsRouteImport.update({
  id: '/user-referrals',
  path: '/user-referrals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserKycRoute = AdminUserKycRouteImport.update({
  id: '/user-kyc',
  path: '/user-kyc',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTradersRoute = AdminTradersRouteImport.update({
  id: '/traders',
  path: '/traders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotifyRoute = AdminNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMeRoute = AdminMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCopyTradingRoute = AdminCopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copy-trading': typeof AdminCopyTradingRoute
  '/me': typeof AdminMeRoute
  '/notify': typeof AdminNotifyRoute
  '/settings': typeof AdminSettingsRoute
  '/staff': typeof AdminStaffRoute
  '/traders': typeof AdminTradersRoute
  '/transactions': typeof AdminTransactionsRoute
  '/user-kyc': typeof AdminUserKycRoute
  '/user-referrals': typeof AdminUserReferralsRoute
  '/users': typeof AdminUsersRoute
  '/forgot': typeof AuthForgotRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/operations': typeof AuthOperationsRoute
  '/register': typeof AuthRegisterRoute
  '/copy': typeof DashboardCopyRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deposit': typeof DashboardDepositRoute
  '/kyc': typeof DashboardKycRoute
  '/profile': typeof DashboardProfileRoute
  '/section': typeof DashboardSectionRoute
  '/withdrawal': typeof DashboardWithdrawalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copy-trading': typeof AdminCopyTradingRoute
  '/me': typeof AdminMeRoute
  '/notify': typeof AdminNotifyRoute
  '/settings': typeof AdminSettingsRoute
  '/staff': typeof AdminStaffRoute
  '/traders': typeof AdminTradersRoute
  '/transactions': typeof AdminTransactionsRoute
  '/user-kyc': typeof AdminUserKycRoute
  '/user-referrals': typeof AdminUserReferralsRoute
  '/users': typeof AdminUsersRoute
  '/forgot': typeof AuthForgotRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/operations': typeof AuthOperationsRoute
  '/register': typeof AuthRegisterRoute
  '/copy': typeof DashboardCopyRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deposit': typeof DashboardDepositRoute
  '/kyc': typeof DashboardKycRoute
  '/profile': typeof DashboardProfileRoute
  '/section': typeof DashboardSectionRoute
  '/withdrawal': typeof DashboardWithdrawalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_admin/copy-trading': typeof AdminCopyTradingRoute
  '/_admin/me': typeof AdminMeRoute
  '/_admin/notify': typeof AdminNotifyRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/staff': typeof AdminStaffRoute
  '/_admin/traders': typeof AdminTradersRoute
  '/_admin/transactions': typeof AdminTransactionsRoute
  '/_admin/user-kyc': typeof AdminUserKycRoute
  '/_admin/user-referrals': typeof AdminUserReferralsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_auth/forgot': typeof AuthForgotRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/logout': typeof AuthLogoutRoute
  '/_auth/operations': typeof AuthOperationsRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_dashboard/copy': typeof DashboardCopyRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/deposit': typeof DashboardDepositRoute
  '/_dashboard/kyc': typeof DashboardKycRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/section': typeof DashboardSectionRoute
  '/_dashboard/withdrawal': typeof DashboardWithdrawalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/copy-trading'
    | '/me'
    | '/notify'
    | '/settings'
    | '/staff'
    | '/traders'
    | '/transactions'
    | '/user-kyc'
    | '/user-referrals'
    | '/users'
    | '/forgot'
    | '/login'
    | '/logout'
    | '/operations'
    | '/register'
    | '/copy'
    | '/dashboard'
    | '/deposit'
    | '/kyc'
    | '/profile'
    | '/section'
    | '/withdrawal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/copy-trading'
    | '/me'
    | '/notify'
    | '/settings'
    | '/staff'
    | '/traders'
    | '/transactions'
    | '/user-kyc'
    | '/user-referrals'
    | '/users'
    | '/forgot'
    | '/login'
    | '/logout'
    | '/operations'
    | '/register'
    | '/copy'
    | '/dashboard'
    | '/deposit'
    | '/kyc'
    | '/profile'
    | '/section'
    | '/withdrawal'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_dashboard'
    | '/_admin/copy-trading'
    | '/_admin/me'
    | '/_admin/notify'
    | '/_admin/settings'
    | '/_admin/staff'
    | '/_admin/traders'
    | '/_admin/transactions'
    | '/_admin/user-kyc'
    | '/_admin/user-referrals'
    | '/_admin/users'
    | '/_auth/forgot'
    | '/_auth/login'
    | '/_auth/logout'
    | '/_auth/operations'
    | '/_auth/register'
    | '/_dashboard/copy'
    | '/_dashboard/dashboard'
    | '/_dashboard/deposit'
    | '/_dashboard/kyc'
    | '/_dashboard/profile'
    | '/_dashboard/section'
    | '/_dashboard/withdrawal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/withdrawal': {
      id: '/_dashboard/withdrawal'
      path: '/withdrawal'
      fullPath: '/withdrawal'
      preLoaderRoute: typeof DashboardWithdrawalRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/section': {
      id: '/_dashboard/section'
      path: '/section'
      fullPath: '/section'
      preLoaderRoute: typeof DashboardSectionRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/kyc': {
      id: '/_dashboard/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof DashboardKycRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/deposit': {
      id: '/_dashboard/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DashboardDepositRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/copy': {
      id: '/_dashboard/copy'
      path: '/copy'
      fullPath: '/copy'
      preLoaderRoute: typeof DashboardCopyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/operations': {
      id: '/_auth/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthOperationsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot': {
      id: '/_auth/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/user-referrals': {
      id: '/_admin/user-referrals'
      path: '/user-referrals'
      fullPath: '/user-referrals'
      preLoaderRoute: typeof AdminUserReferralsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/user-kyc': {
      id: '/_admin/user-kyc'
      path: '/user-kyc'
      fullPath: '/user-kyc'
      preLoaderRoute: typeof AdminUserKycRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/transactions': {
      id: '/_admin/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/traders': {
      id: '/_admin/traders'
      path: '/traders'
      fullPath: '/traders'
      preLoaderRoute: typeof AdminTradersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/staff': {
      id: '/_admin/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/notify': {
      id: '/_admin/notify'
      path: '/notify'
      fullPath: '/notify'
      preLoaderRoute: typeof AdminNotifyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/me': {
      id: '/_admin/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AdminMeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/copy-trading': {
      id: '/_admin/copy-trading'
      path: '/copy-trading'
      fullPath: '/copy-trading'
      preLoaderRoute: typeof AdminCopyTradingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCopyTradingRoute: typeof AdminCopyTradingRoute
  AdminMeRoute: typeof AdminMeRoute
  AdminNotifyRoute: typeof AdminNotifyRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTradersRoute: typeof AdminTradersRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUserKycRoute: typeof AdminUserKycRoute
  AdminUserReferralsRoute: typeof AdminUserReferralsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCopyTradingRoute: AdminCopyTradingRoute,
  AdminMeRoute: AdminMeRoute,
  AdminNotifyRoute: AdminNotifyRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTradersRoute: AdminTradersRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUserKycRoute: AdminUserKycRoute,
  AdminUserReferralsRoute: AdminUserReferralsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthOperationsRoute: typeof AuthOperationsRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthOperationsRoute: AuthOperationsRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardCopyRoute: typeof DashboardCopyRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDepositRoute: typeof DashboardDepositRoute
  DashboardKycRoute: typeof DashboardKycRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSectionRoute: typeof DashboardSectionRoute
  DashboardWithdrawalRoute: typeof DashboardWithdrawalRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCopyRoute: DashboardCopyRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDepositRoute: DashboardDepositRoute,
  DashboardKycRoute: DashboardKycRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSectionRoute: DashboardSectionRoute,
  DashboardWithdrawalRoute: DashboardWithdrawalRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
