/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeTradingRouteImport } from './routes/_home/trading'
import { Route as HomeEducationRouteImport } from './routes/_home/education'
import { Route as HomeContactRouteImport } from './routes/_home/contact'
import { Route as HomeCompanyRouteImport } from './routes/_home/company'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as DashboardWithdrawalRouteImport } from './routes/_dashboard/withdrawal'
import { Route as DashboardSupportRouteImport } from './routes/_dashboard/support'
import { Route as DashboardSectionRouteImport } from './routes/_dashboard/section'
import { Route as DashboardReferralRouteImport } from './routes/_dashboard/referral'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardMarketRouteImport } from './routes/_dashboard/market'
import { Route as DashboardLogoutRouteImport } from './routes/_dashboard/logout'
import { Route as DashboardKycRouteImport } from './routes/_dashboard/kyc'
import { Route as DashboardHistoryRouteImport } from './routes/_dashboard/history'
import { Route as DashboardDepositRouteImport } from './routes/_dashboard/deposit'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCopyRouteImport } from './routes/_dashboard/copy'
import { Route as AuthUnauthorizedRouteImport } from './routes/_auth/unauthorized'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthOperationsRouteImport } from './routes/_auth/operations'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotRouteImport } from './routes/_auth/forgot'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminUserReferralsRouteImport } from './routes/_admin/user-referrals'
import { Route as AdminUserKycRouteImport } from './routes/_admin/user-kyc'
import { Route as AdminTransactionsRouteImport } from './routes/_admin/transactions'
import { Route as AdminTradesRouteImport } from './routes/_admin/trades'
import { Route as AdminTradersRouteImport } from './routes/_admin/traders'
import { Route as AdminStaffRouteImport } from './routes/_admin/staff'
import { Route as AdminSignoutRouteImport } from './routes/_admin/signout'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminMeRouteImport } from './routes/_admin/me'
import { Route as AdminCopyTradingRouteImport } from './routes/_admin/copy-trading'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeTradingRoute = HomeTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeEducationRoute = HomeEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeContactRoute = HomeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCompanyRoute = HomeCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRouteRoute,
} as any)
const DashboardWithdrawalRoute = DashboardWithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSectionRoute = DashboardSectionRouteImport.update({
  id: '/section',
  path: '/section',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReferralRoute = DashboardReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMarketRoute = DashboardMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLogoutRoute = DashboardLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKycRoute = DashboardKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDepositRoute = DashboardDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCopyRoute = DashboardCopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOperationsRoute = AuthOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserReferralsRoute = AdminUserReferralsRouteImport.update({
  id: '/user-referrals',
  path: '/user-referrals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserKycRoute = AdminUserKycRouteImport.update({
  id: '/user-kyc',
  path: '/user-kyc',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTradesRoute = AdminTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTradersRoute = AdminTradersRouteImport.update({
  id: '/traders',
  path: '/traders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSignoutRoute = AdminSignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMeRoute = AdminMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCopyTradingRoute = AdminCopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/copy-trading': typeof AdminCopyTradingRoute
  '/me': typeof AdminMeRoute
  '/settings': typeof AdminSettingsRoute
  '/signout': typeof AdminSignoutRoute
  '/staff': typeof AdminStaffRoute
  '/traders': typeof AdminTradersRoute
  '/trades': typeof AdminTradesRoute
  '/transactions': typeof AdminTransactionsRoute
  '/user-kyc': typeof AdminUserKycRoute
  '/user-referrals': typeof AdminUserReferralsRoute
  '/users': typeof AdminUsersRoute
  '/forgot': typeof AuthForgotRoute
  '/login': typeof AuthLoginRoute
  '/operations': typeof AuthOperationsRoute
  '/register': typeof AuthRegisterRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/copy': typeof DashboardCopyRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deposit': typeof DashboardDepositRoute
  '/history': typeof DashboardHistoryRoute
  '/kyc': typeof DashboardKycRoute
  '/logout': typeof DashboardLogoutRoute
  '/market': typeof DashboardMarketRoute
  '/profile': typeof DashboardProfileRoute
  '/referral': typeof DashboardReferralRoute
  '/section': typeof DashboardSectionRoute
  '/support': typeof DashboardSupportRoute
  '/withdrawal': typeof DashboardWithdrawalRoute
  '/about': typeof HomeAboutRoute
  '/company': typeof HomeCompanyRoute
  '/contact': typeof HomeContactRoute
  '/education': typeof HomeEducationRoute
  '/trading': typeof HomeTradingRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/copy-trading': typeof AdminCopyTradingRoute
  '/me': typeof AdminMeRoute
  '/settings': typeof AdminSettingsRoute
  '/signout': typeof AdminSignoutRoute
  '/staff': typeof AdminStaffRoute
  '/traders': typeof AdminTradersRoute
  '/trades': typeof AdminTradesRoute
  '/transactions': typeof AdminTransactionsRoute
  '/user-kyc': typeof AdminUserKycRoute
  '/user-referrals': typeof AdminUserReferralsRoute
  '/users': typeof AdminUsersRoute
  '/forgot': typeof AuthForgotRoute
  '/login': typeof AuthLoginRoute
  '/operations': typeof AuthOperationsRoute
  '/register': typeof AuthRegisterRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/copy': typeof DashboardCopyRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deposit': typeof DashboardDepositRoute
  '/history': typeof DashboardHistoryRoute
  '/kyc': typeof DashboardKycRoute
  '/logout': typeof DashboardLogoutRoute
  '/market': typeof DashboardMarketRoute
  '/profile': typeof DashboardProfileRoute
  '/referral': typeof DashboardReferralRoute
  '/section': typeof DashboardSectionRoute
  '/support': typeof DashboardSupportRoute
  '/withdrawal': typeof DashboardWithdrawalRoute
  '/about': typeof HomeAboutRoute
  '/company': typeof HomeCompanyRoute
  '/contact': typeof HomeContactRoute
  '/education': typeof HomeEducationRoute
  '/trading': typeof HomeTradingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_home': typeof HomeRouteRouteWithChildren
  '/_admin/copy-trading': typeof AdminCopyTradingRoute
  '/_admin/me': typeof AdminMeRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/signout': typeof AdminSignoutRoute
  '/_admin/staff': typeof AdminStaffRoute
  '/_admin/traders': typeof AdminTradersRoute
  '/_admin/trades': typeof AdminTradesRoute
  '/_admin/transactions': typeof AdminTransactionsRoute
  '/_admin/user-kyc': typeof AdminUserKycRoute
  '/_admin/user-referrals': typeof AdminUserReferralsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_auth/forgot': typeof AuthForgotRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/operations': typeof AuthOperationsRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/unauthorized': typeof AuthUnauthorizedRoute
  '/_dashboard/copy': typeof DashboardCopyRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/deposit': typeof DashboardDepositRoute
  '/_dashboard/history': typeof DashboardHistoryRoute
  '/_dashboard/kyc': typeof DashboardKycRoute
  '/_dashboard/logout': typeof DashboardLogoutRoute
  '/_dashboard/market': typeof DashboardMarketRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/referral': typeof DashboardReferralRoute
  '/_dashboard/section': typeof DashboardSectionRoute
  '/_dashboard/support': typeof DashboardSupportRoute
  '/_dashboard/withdrawal': typeof DashboardWithdrawalRoute
  '/_home/about': typeof HomeAboutRoute
  '/_home/company': typeof HomeCompanyRoute
  '/_home/contact': typeof HomeContactRoute
  '/_home/education': typeof HomeEducationRoute
  '/_home/trading': typeof HomeTradingRoute
  '/_home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/copy-trading'
    | '/me'
    | '/settings'
    | '/signout'
    | '/staff'
    | '/traders'
    | '/trades'
    | '/transactions'
    | '/user-kyc'
    | '/user-referrals'
    | '/users'
    | '/forgot'
    | '/login'
    | '/operations'
    | '/register'
    | '/unauthorized'
    | '/copy'
    | '/dashboard'
    | '/deposit'
    | '/history'
    | '/kyc'
    | '/logout'
    | '/market'
    | '/profile'
    | '/referral'
    | '/section'
    | '/support'
    | '/withdrawal'
    | '/about'
    | '/company'
    | '/contact'
    | '/education'
    | '/trading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/copy-trading'
    | '/me'
    | '/settings'
    | '/signout'
    | '/staff'
    | '/traders'
    | '/trades'
    | '/transactions'
    | '/user-kyc'
    | '/user-referrals'
    | '/users'
    | '/forgot'
    | '/login'
    | '/operations'
    | '/register'
    | '/unauthorized'
    | '/copy'
    | '/dashboard'
    | '/deposit'
    | '/history'
    | '/kyc'
    | '/logout'
    | '/market'
    | '/profile'
    | '/referral'
    | '/section'
    | '/support'
    | '/withdrawal'
    | '/about'
    | '/company'
    | '/contact'
    | '/education'
    | '/trading'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_dashboard'
    | '/_home'
    | '/_admin/copy-trading'
    | '/_admin/me'
    | '/_admin/settings'
    | '/_admin/signout'
    | '/_admin/staff'
    | '/_admin/traders'
    | '/_admin/trades'
    | '/_admin/transactions'
    | '/_admin/user-kyc'
    | '/_admin/user-referrals'
    | '/_admin/users'
    | '/_auth/forgot'
    | '/_auth/login'
    | '/_auth/operations'
    | '/_auth/register'
    | '/_auth/unauthorized'
    | '/_dashboard/copy'
    | '/_dashboard/dashboard'
    | '/_dashboard/deposit'
    | '/_dashboard/history'
    | '/_dashboard/kyc'
    | '/_dashboard/logout'
    | '/_dashboard/market'
    | '/_dashboard/profile'
    | '/_dashboard/referral'
    | '/_dashboard/section'
    | '/_dashboard/support'
    | '/_dashboard/withdrawal'
    | '/_home/about'
    | '/_home/company'
    | '/_home/contact'
    | '/_home/education'
    | '/_home/trading'
    | '/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/trading': {
      id: '/_home/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof HomeTradingRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/education': {
      id: '/_home/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof HomeEducationRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/contact': {
      id: '/_home/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof HomeContactRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/company': {
      id: '/_home/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof HomeCompanyRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_dashboard/withdrawal': {
      id: '/_dashboard/withdrawal'
      path: '/withdrawal'
      fullPath: '/withdrawal'
      preLoaderRoute: typeof DashboardWithdrawalRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/support': {
      id: '/_dashboard/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/section': {
      id: '/_dashboard/section'
      path: '/section'
      fullPath: '/section'
      preLoaderRoute: typeof DashboardSectionRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/referral': {
      id: '/_dashboard/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof DashboardReferralRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/market': {
      id: '/_dashboard/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof DashboardMarketRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/logout': {
      id: '/_dashboard/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof DashboardLogoutRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/kyc': {
      id: '/_dashboard/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof DashboardKycRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/history': {
      id: '/_dashboard/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/deposit': {
      id: '/_dashboard/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DashboardDepositRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/copy': {
      id: '/_dashboard/copy'
      path: '/copy'
      fullPath: '/copy'
      preLoaderRoute: typeof DashboardCopyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/unauthorized': {
      id: '/_auth/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/operations': {
      id: '/_auth/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthOperationsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot': {
      id: '/_auth/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/user-referrals': {
      id: '/_admin/user-referrals'
      path: '/user-referrals'
      fullPath: '/user-referrals'
      preLoaderRoute: typeof AdminUserReferralsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/user-kyc': {
      id: '/_admin/user-kyc'
      path: '/user-kyc'
      fullPath: '/user-kyc'
      preLoaderRoute: typeof AdminUserKycRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/transactions': {
      id: '/_admin/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/trades': {
      id: '/_admin/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AdminTradesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/traders': {
      id: '/_admin/traders'
      path: '/traders'
      fullPath: '/traders'
      preLoaderRoute: typeof AdminTradersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/staff': {
      id: '/_admin/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/signout': {
      id: '/_admin/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof AdminSignoutRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/me': {
      id: '/_admin/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AdminMeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/copy-trading': {
      id: '/_admin/copy-trading'
      path: '/copy-trading'
      fullPath: '/copy-trading'
      preLoaderRoute: typeof AdminCopyTradingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCopyTradingRoute: typeof AdminCopyTradingRoute
  AdminMeRoute: typeof AdminMeRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSignoutRoute: typeof AdminSignoutRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTradersRoute: typeof AdminTradersRoute
  AdminTradesRoute: typeof AdminTradesRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUserKycRoute: typeof AdminUserKycRoute
  AdminUserReferralsRoute: typeof AdminUserReferralsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCopyTradingRoute: AdminCopyTradingRoute,
  AdminMeRoute: AdminMeRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSignoutRoute: AdminSignoutRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTradersRoute: AdminTradersRoute,
  AdminTradesRoute: AdminTradesRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUserKycRoute: AdminUserKycRoute,
  AdminUserReferralsRoute: AdminUserReferralsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOperationsRoute: typeof AuthOperationsRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOperationsRoute: AuthOperationsRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardCopyRoute: typeof DashboardCopyRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDepositRoute: typeof DashboardDepositRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardKycRoute: typeof DashboardKycRoute
  DashboardLogoutRoute: typeof DashboardLogoutRoute
  DashboardMarketRoute: typeof DashboardMarketRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReferralRoute: typeof DashboardReferralRoute
  DashboardSectionRoute: typeof DashboardSectionRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardWithdrawalRoute: typeof DashboardWithdrawalRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCopyRoute: DashboardCopyRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDepositRoute: DashboardDepositRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardKycRoute: DashboardKycRoute,
  DashboardLogoutRoute: DashboardLogoutRoute,
  DashboardMarketRoute: DashboardMarketRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReferralRoute: DashboardReferralRoute,
  DashboardSectionRoute: DashboardSectionRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardWithdrawalRoute: DashboardWithdrawalRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeCompanyRoute: typeof HomeCompanyRoute
  HomeContactRoute: typeof HomeContactRoute
  HomeEducationRoute: typeof HomeEducationRoute
  HomeTradingRoute: typeof HomeTradingRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeCompanyRoute: HomeCompanyRoute,
  HomeContactRoute: HomeContactRoute,
  HomeEducationRoute: HomeEducationRoute,
  HomeTradingRoute: HomeTradingRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
